#name="ioane"
# name არის ცვლადი
# = არის ცვლადისთვის მნიშვნელობის მიმნიჭებელი სიმბოლო
# ioane არის ცვლადისთვის მნიშვნელობა

me = "me"
am = "var"
surname = "bendeliani"
age2 = "wlis"
activity1 = "vswavlob programirebas"
plus = "da"
activity2 = "davdivar dziudoze"
# პრინტ ფუნქციას გადაეცემა ეკრანზე გამოსატანი ობიექტი

name ="ioane" # ეს არის str (string) ტიპის ცვლადი
age = 14 # ეს არის int ( integer ) მთელი რიცხვი
height = 168,5 # ეს არის float ტიპის ცვლადი ( ათწილადი )
#boolean (bool) ტიპის ცვლადი

knows_programming = True #True ან False
is_ugly = False #snakecase (უბრალოდ წერის სტილი სტანდარტულად)

isUgly = False # ჯავასკრიპტული camelcase

print( name + " " + surname)
print(name + " " + str(14))
print(me + " " + am + " " + name + " " + surname + " " + str(age) + " " + age2 + " " + activity1 + " " + plus + " " + activity2)